- params:
    git:
      branches:
        - main
      repoName: "frogbot-monorepo-demo"
    scan:
      projects:
        - workingDirs:
            - frontend
        - workingDirs:
            - backend
          pipRequirementsFile: requirements.txt
